### ISSUE TITLE
unable to launch the application 

### ISSUE THREAD

**Issue by saro199** [DanWahlin/Angular-NodeJS-MongoDB-CustomersService#3]
I was able to start the app using npm start, and DB seeder loads and everything good,
When launching the application in chrome browser the
Index.html is not able to identify the following js files and it stays in loading in chrome browser

<script src="lib/shim.min.js"></script>
<script src="lib/zone.js"></script>
<script src="lib/system.src.js"></script>
<script src="systemjs.config.js"></script>
<script>
  System.import('app').catch(function(err){ console.error(err); });
</script>
Following is the error in chrome console.

shim.min.js:1 Uncaught SyntaxError: Unexpected token <
zone.js:1 Uncaught SyntaxError: Unexpected token <
system.src.js:1 Uncaught SyntaxError: Unexpected token <
systemjs.config.js:50 Uncaught ReferenceError: System is not defined
at systemjs.config.js:50
at systemjs.config.js:61
(anonymous) @ systemjs.config.js:50
(anonymous) @ systemjs.config.js:61
(index):22 Uncaught ReferenceError: System is not defined
at (index):22
(anonymous) @ (index):22

**Comment by DanWahlin** [comment]
Hi again. I'll mention what I mentioned in the previous comment. Did you run the gulp task mentioned in the readme? If you did you should see scripts added into the lib folder if it ran without issue. If you don't see any scripts in there then something may have gone wrong during the process.

**Comment by saro199** [comment]
My Bad was looking the root level readme. Thanks a lot works like a charm.
Very nice tutorial in plural sight.

**Comment by DanWahlin** [comment]
No problem - glad you got it going!
